name: "Plan AWS Ec2 infrastructure"

on:
  pull_request:
    branches-ignore:
      - master
    types:
      - opened
      - synchronize
      - reopened

jobs:
  build-test:
    runs-on: "ubuntu-latest"

    defaults:
      run:
        working-directory: tfmp-codes/vm-deploy

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.TF_VAR_AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.TF_VAR_AWS_SECRET }}
          aws-region: ap-south-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

      # - name: Terraform apply
      #   run: terraform apply --auto-approve
    